from django.db import models
import uuid


class ExternalTeamRegistration(models.Model):
    application_id = models.UUIDField(unique=True, default=uuid.uuid4)
    team_name = models.CharField(max_length=100)
    college_name = models.CharField(max_length=100)
    college_address = models.CharField(max_length=300)
    captain_name = models.CharField(max_length=100)
    aadhar_number = models.IntegerField()
    email = models.EmailField()
    contact_number = models.IntegerField()
    whatsapp_number = models.IntegerField()
    vice_captain_name = models.CharField(max_length=100)
    vice_aadhar_number = models.IntegerField()
    vice_email = models.EmailField()
    vice_contact_number = models.IntegerField()
    player_name3 = models.CharField(max_length=100)
    player_registration_number3 = models.IntegerField()
    player_name4 = models.CharField(max_length=100)
    player_registration_number4 = models.IntegerField()
    player_name5 = models.CharField(max_length=100)
    player_registration_number5 = models.IntegerField()
    player_name6 = models.CharField(max_length=100)
    player_registration_number6 = models.IntegerField()
    player_name7 = models.CharField(max_length=100)
    player_registration_number7 = models.IntegerField()
    player_name8 = models.CharField(max_length=100)
    player_registration_number8 = models.IntegerField()
    player_name9 = models.CharField(max_length=100)
    player_registration_number9 = models.IntegerField()
    player_name10 = models.CharField(max_length=100)
    player_registration_number10 = models.IntegerField()
    player_name11 = models.CharField(max_length=100)
    player_registration_number11 = models.IntegerField()
    player_name12 = models.CharField(max_length=100)
    player_registration_number12 = models.IntegerField()
    player_name13 = models.CharField(max_length=100)
    player_registration_number13 = models.IntegerField()
    player_name14 = models.CharField(max_length=100)
    player_registration_number14 = models.IntegerField()
    player_name15 = models.CharField(max_length=100)
    player_registration_number15 = models.IntegerField()
    payment_id = models.CharField(max_length=255, blank=True, null=True)
    accommodation = models.BooleanField()

    def __str__(self):
        return self.team_name

    # def __init__(self):
    #     super(ExternalTeamRegistration, self).__init__()
    #     self.application_id = str(uuid.uuid4())


class InternalTeamRegistration(models.Model):
    application_id = models.UUIDField(unique=True, default=uuid.uuid4)
    team_name = models.CharField(max_length=100)
    captain_name = models.CharField(max_length=100)
    captain_registration_number = models.IntegerField()
    email = models.EmailField()
    contact_number = models.IntegerField()
    whatsapp_number = models.IntegerField()
    vice_captain_name = models.CharField(max_length=100)
    vice_captain_registration_number = models.IntegerField()
    vice_email = models.EmailField()
    vice_contact_number = models.IntegerField()
    player_name3 = models.CharField(max_length=100)
    player_registration_number3 = models.IntegerField()
    player_name4 = models.CharField(max_length=100)
    player_registration_number4 = models.IntegerField()
    player_name5 = models.CharField(max_length=100)
    player_registration_number5 = models.IntegerField()
    player_name6 = models.CharField(max_length=100)
    player_registration_number6 = models.IntegerField()
    player_name7 = models.CharField(max_length=100)
    player_registration_number7 = models.IntegerField()
    player_name8 = models.CharField(max_length=100)
    player_registration_number8 = models.IntegerField()
    player_name9 = models.CharField(max_length=100)
    player_registration_number9 = models.IntegerField()
    player_name10 = models.CharField(max_length=100)
    player_registration_number10 = models.IntegerField()
    player_name11 = models.CharField(max_length=100)
    player_registration_number11 = models.IntegerField()
    player_name12 = models.CharField(max_length=100)
    player_registration_number12 = models.IntegerField()
    player_name13 = models.CharField(max_length=100)
    player_registration_number13 = models.IntegerField()
    player_name14 = models.CharField(max_length=100)
    player_registration_number14 = models.IntegerField()
    player_name15 = models.CharField(max_length=100)
    player_registration_number15 = models.IntegerField()
    payment_id = models.CharField(max_length=255, blank=True, null=True)
    accommodation = models.BooleanField()

    def __str__(self):
        return self.team_name
