# Generated by Django 2.2.6 on 2019-10-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=1000)),
                ('tagline', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('fee', models.FloatField()),
                ('poster', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
