# Generated by Django 2.2.6 on 2019-10-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='captain_registration_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerform',
            name='vice_captain_registration_number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
