# Generated by Django 2.2.2 on 2019-10-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0002_auto_20191008_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=1000)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
