# Generated by Django 2.2.6 on 2019-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0003_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AddField(
            model_name='registerform',
            name='payment_status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
