# Generated by Django 2.2.6 on 2019-10-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0005_auto_20191010_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalteamregistration',
            name='captain_reg',
        ),
    ]
