# Generated by Django 2.2.6 on 2019-10-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0006_remove_internalteamregistration_captain_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalteamregistration',
            name='whatsapp_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalteamregistration',
            name='whatsapp_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
