# Generated by Django 2.2.6 on 2019-10-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0007_auto_20191010_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalteamregistration',
            name='vice_caption_reg',
        ),
    ]
