# Generated by Django 2.2.6 on 2019-10-16 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0009_auto_20191010_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalteamregistration',
            name='application_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='internalteamregistration',
            name='application_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
