# Generated by Django 2.2.6 on 2019-10-16 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0010_auto_20191016_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalteamregistration',
            name='id',
        ),
        migrations.RemoveField(
            model_name='internalteamregistration',
            name='id',
        ),
        migrations.AlterField(
            model_name='externalteamregistration',
            name='application_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internalteamregistration',
            name='application_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
