# Generated by Django 2.2.6 on 2019-10-16 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0011_auto_20191016_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalteamregistration',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalteamregistration',
            name='application_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
